version: '3.9'

services:
  crudservice:
    container_name: crud
    build: .
    ports:
      - "8080:8080"
    volumes:
      - image_data:/app/images  # Use a named volume
    networks:
     - test

volumes:
  image_data:  # Define the named volume

networks:
  test:
    external: true