version: '3.9'

services:
  crudservice:
    container_name: crud
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
    networks:
     - test

networks:
  test:
    external: true