version: '3.9'

services:
  crudservice:
    container_name: crud
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images  # Mount the local images directory
    user: "1000:1000"  # Set to your host user UID:GID (adjust these numbers based on your user)
    networks:
     - test

networks:
  test:
    external: true