basePath: /
definitions:
  main.RecognizeResponse:
    properties:
      matched_image:
        type: string
      processing_time_ms:
        type: integer
      result:
        type: string
      similarity:
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: support@imageapi.com
    name: API Support
  description: API service for comparing images
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Image Recognition API
  version: "1.1"
paths:
  /admin/add:
    post:
      consumes:
      - multipart/form-data
      description: Add a new reference image to the database
      parameters:
      - description: Image to add
        in: formData
        name: image
        required: true
        type: file
      - description: Custom name for the image
        in: formData
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add new image to database
      tags:
      - Image Database Management
  /admin/hello:
    get:
      description: hello
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Hello
      tags:
      - Image Database Management
  /recognize:
    post:
      consumes:
      - multipart/form-data
      description: Compare uploaded image against database
      parameters:
      - description: Image to check
        in: formData
        name: image
        required: true
        type: file
      - description: Similarity threshold (0-100, default 80)
        in: formData
        name: threshold
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.RecognizeResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Recognize image
      tags:
      - Image Recognition
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
