definitions:
  main.CompareResponse:
    properties:
      match:
        type: boolean
      processing_time_ms:
        type: integer
      similarity:
        type: number
    type: object
info:
  contact: {}
paths:
  /admin/add:
    post:
      consumes:
      - multipart/form-data
      description: Add a new reference image to the database
      parameters:
      - description: Image to add
        in: formData
        name: image
        required: true
        type: file
      - description: Custom name for the image
        in: formData
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add new image to database
      tags:
      - Image Database Management
  /admin/hello:
    get:
      description: hello
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Hello
      tags:
      - Image Database Management
  /compare:
    post:
      consumes:
      - multipart/form-data
      description: Compare two uploaded images and return similarity
      parameters:
      - description: First image to compare
        in: formData
        name: image1
        required: true
        type: file
      - description: Second image to compare
        in: formData
        name: image2
        required: true
        type: file
      - description: Similarity threshold (0-100, default 85)
        in: formData
        name: threshold
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.CompareResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Compare two images
      tags:
      - Image Comparison
swagger: "2.0"
